#!/bin/sh
# Script to start/stop a hostapd-based access point
#
# Sample start call "control_ap start wlan0 eth0"
# Stop with "control_ap stop"
#

case "$1" in
start)
	if [ $# -ne 3 ]
	then
	  echo "Usage: $0 start AP_iface NET_iface"
	  exit 1
	fi
;;
stop)
	if [ $# -ne 1 ]
	then
	  echo "Usage: $0 stop"
	  exit 1
	fi
;;
*)
  echo "Usage:"
	echo "$0 start AP-iface net_iface"
	echo "or"
	echo "$0 stop"
  exit 1
  ;;
esac

# Symbols for needed programs
IPTABLES=/sbin/iptables
IFCONFIG=/sbin/ifconfig
DHCPD=/usr/sbin/dhcpd
HOSTAPD=/home/pi/rtl8188eu/hostapd-0.8/hostapd/hostapd

AP_INTERFACE=$2
EXTERNAL_INTERFACE=$3

AP_PREFIX=192.168.0

NAME_SERVER=8.8.8.8

AP_CHANNEL=11
AP_SSID=rtwap
WPA_SECRET="87654321"
ENCRYPT_MODE=2
DRIVER=rtl871xdrv

DHCPCONF=~/dhcpd.conf
HOSTAPDCONF=~/hostapd.conf

function check_leases_file() {
  if [ ! -f /var/lib/dhcp/db/dhcpd.leases ]; then
    mkdir -p /var/lib/dhcp/db
    touch /var/lib/dhcp/db/dhcpd.leases
  fi
}

function config_dhcpd () {
  check_leases_file
  cat > $DHCPCONF << EOF
option domain-name-servers $NAME_SERVER;
default-lease-time 600;
max-lease-time 7200;
ddns-update-style none; ddns-updates off;
subnet $AP_PREFIX.0 netmask 255.255.255.0 {
  range $AP_PREFIX.200 $AP_PREFIX.229;
  option subnet-mask 255.255.255.0;
  option broadcast-address $AP_PREFIX.255;
  option routers $AP_PREFIX.1;
}
EOF
}

function start_dhcpd() {
  $DHCPD -cf $DHCPCONF $AP_INTERFACE
}

function config_hostapd() {
  cat > $HOSTAPDCONF << EOF
auth_algs=1
beacon_int=100
country_code=ES
ctrl_interface_group=0
ctrl_interface=/var/run/hostapd
dtim_period=2
dump_file=/tmp/hostapd.dump
fragm_threshold=2346
#ht_capab=[HT40-][SHORT-GI-20][SHORT-GI-40][MAX-AMSDU-7935][DSSS_CCK-40]
#ieee80211d=1
ieee80211n=1
ignore_broadcast_ssid=0
logger_stdout=-1
logger_stdout_level=2
logger_syslog=-1
logger_syslog_level=2
macaddr_acl=0
max_num_sta=255
rts_threshold=2347
wmm_ac_be_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmax=10
wmm_ac_be_cwmin=4
wmm_ac_be_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_bk_aifs=7
wmm_ac_bk_cwmax=10
wmm_ac_bk_cwmin=4
wmm_ac_bk_txop_limit=0
wmm_ac_vi_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmax=4
wmm_ac_vi_cwmin=3
wmm_ac_vi_txop_limit=94
wmm_ac_vo_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_cwmin=2
wmm_ac_vo_txop_limit=47
wmm_enabled=1
interface=$AP_INTERFACE
ssid=$AP_SSID
driver=$DRIVER
hw_mode=g
channel=$AP_CHANNEL
wpa=$ENCRYPT_MODE
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP
wpa_passphrase=$WPA_SECRET
EOF
}

function start_hostapd() {
  $HOSTAPD -dd -B $HOSTAPDCONF
}

function stop_hostapd() {
  killall hostapd
  rm -f $HOSTAPDCONF
}

function stop_dhcpd() {
  killall dhcpd
  rm -f $DHCPCONF
}

function disable_ip_forward() {
  echo 0 > /proc/sys/net/ipv4/ip_forward
}

function enable_ip_forward() {
  echo 1 > /proc/sys/net/ipv4/ip_forward
}

function configure_ap_interface() {
  $IFCONFIG $AP_INTERFACE down
  $IFCONFIG $AP_INTERFACE up
  $IFCONFIG $AP_INTERFACE $AP_PREFIX.1
}

function setup_forwarding() {
  $IPTABLES -t nat -A POSTROUTING -o $EXTERNAL_INTERFACE -j MASQUERADE
  $IPTABLES -A FORWARD -i $EXTERNAL_INTERFACE -o $AP_INTERFACE -m state \
    --state RELATED,ESTABLISHED -j ACCEPT
  $IPTABLES -A FORWARD -i $AP_INTERFACE -o $EXTERNAL_INTERFACE -j ACCEPT

  configure_ap_interface
}

case "$1" in
  start)
    echo "Starting AP mode for $AP_INTERFACE at address $AP_PREFIX.1"
    disable_ip_forward
    stop_hostapd
    stop_dhcpd
    setup_forwarding
    config_dhcpd
    start_dhcpd
    config_hostapd
    enable_ip_forward
    start_hostapd
    ;;
  stop)
    echo "Stopping AP mode"
    stop_hostapd
    stop_dhcpd
    ;;
esac
